name: BiCEP
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn=0.24.1
  - tornado=6.1
  - future=0.18.2
  - pandas=1.3.4
  - ipympl=0.8.7
  - pystan=2.19.0.0
  - ipyfilechooser=0.4.3
  - voila=0.2.4
  - arviz=0.11.4
  - clang_osx-64=12.0.0
  - clangxx_osx-64=12.0.0
  - cartopy=0.18.0
